// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7o-HFVoKJmXT6VEHaOa7nUX06-lp05rw',
    appId: '1:1072682623856:web:49be9fd713e9b8a52865b5',
    messagingSenderId: '1072682623856',
    projectId: 'budget-app-8d',
    authDomain: 'budget-app-8d.firebaseapp.com',
    storageBucket: 'budget-app-8d.firebasestorage.app',
    measurementId: 'G-6C2DQQ8MXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4xMCehm9Kdu7v9awhxO3drSq_1bOAd8w',
    appId: '1:1072682623856:android:bb1c3b9c05967aec2865b5',
    messagingSenderId: '1072682623856',
    projectId: 'budget-app-8d',
    storageBucket: 'budget-app-8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVFQPtN5N_o_kH2bkPBaOCw5ecmFjp-mE',
    appId: '1:1072682623856:ios:ecdbfb091841463c2865b5',
    messagingSenderId: '1072682623856',
    projectId: 'budget-app-8d',
    storageBucket: 'budget-app-8d.firebasestorage.app',
    androidClientId: '1072682623856-r24148miom2r7f5lu3rc6gsgugt5n1mq.apps.googleusercontent.com',
    iosClientId: '1072682623856-rsa1j7inpg6l40oom4gbi3bjblkei3r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.muskan-poddar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7o-HFVoKJmXT6VEHaOa7nUX06-lp05rw',
    appId: '1:1072682623856:web:e78a3fae6f0294302865b5',
    messagingSenderId: '1072682623856',
    projectId: 'budget-app-8d',
    authDomain: 'budget-app-8d.firebaseapp.com',
    storageBucket: 'budget-app-8d.firebasestorage.app',
    measurementId: 'G-Q0J4TZQQZD',
  );

}